# Generated by Django 5.0.3 on 2024-03-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eid', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mob', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
